tape-admin: respect 'tape in use' in ltfs_unmount
* signal error, since tape can't be used for backup

Signed-off-by: Ralf Zerres <ralf.zerres@networkx.de>

diff --git a/bin/tape-admin b/bin/tape-admin
--- a/bin/tape-admin
+++ b/bin/tape-admin
@@ -716,6 +716,12 @@ ltfs_umount () {
 		       "$ltfs_mountpoint"
 	    fi
 	    return 0
+	elif [ $? -eq 32 ]; then
+	    if [ $verbose -ge 2 ]; then
+		printf "${RED}Error: ${MAGENTA}LTFS tape ${GREEN}'%s'${MAGENTA} is in use!${NO_COLOR}\n" \
+		       "$ltfs_mountpoint"
+	    fi
+	    return 1
 	else
 	    return 1
 	fi
